<a href="https://colab.research.google.com/github/HyunMin-Ju/Start_PyTorch/blob/main/TensorManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy로 텐서 만들기**

출처: 파이토치를 이용한 딥러닝 입문


In [3]:
import numpy as np

In [4]:
#1차원 텐서

t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [6]:
#몇 차원인지 알려주는 ndim
print('Rank of t: ',t.ndim)

#크기를 알려주는 .shape
#(7,)는 (1,7)을 의미한다. 즉 (1,7)은 1x7의 크기를 가지는 벡터이다.
#(2,3)은 2x3이고, (5,)는 1x5이다.
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [7]:
#2d with np

t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


**PyTorch Tensor Allocation**

In [8]:
import torch

In [9]:
#1d tensor with pytorch

t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim()) #현재 텐서의 차원

print(t.shape)#크기1
print(t.size())#크기2

1
torch.Size([7])
torch.Size([7])


In [11]:
#2d with pyTorch

t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [13]:
print(t[:,1]) #첫번째 차원 전체 선택하고 두번째 차원꺼만 가져옴

tensor([ 2.,  5.,  8., 11.])


In [14]:
print(t[:,1].size()) #위에꺼 크기

torch.Size([4])


In [15]:
print(t[:,:-1]) #첫번째 차원 전체 선택하고, 두번째 차원에서 맨마지막에서 첫번째를 제외하고 다 가져옴

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


**BroadCasting**